services:
  app:
    restart: always
    build: .
    ports:
      - '4444:4444'
    env_file: .env
    volumes:
      - ./src:/app/src
    links: 
      - redis
  redis:
    image: redis:6-alpine
    command: redis-server --requirepass 123 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  redis_data: